baseURL = "http://example.org/"
title = "无闻的小站"
theme = "LeaveIt"
languageCode = "zh-CN"

paginate = 12

enableEmoji = true
hasCJKLanguage = true
preserveTaxonomyNames = true

[menu]
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "关于我"
    url = "/about/"
    weight = 4

[params]
    since = 2011
    author = "无闻"
    avatar = "https://avatars2.githubusercontent.com/u/2946214?s=460&v=4"
    subtitle = "抛弃世俗之浮躁，留我钻研之刻苦"
    beian = "浙ICP备20012357号"
    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'
    hidecredits = true

[params.social]
    GitHub = "unknwon"
    Twitter = "jc_unknwon"

[permalinks]
    posts = "/:year/:filename/"

[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true
        [markup.goldmark.parser]
            attribute = true
            autoHeadingID = true
            autoHeadingIDType = "github"
        [markup.goldmark.renderer]
            hardWraps = false
            unsafe = true
            xhtml = false
        [markup.highlight]
            codeFences = true
            guessSyntax = false
            hl_Lines = ""
            lineNoStart = 1
            lineNos = false
            lineNumbersInTable = true
            noClasses = true
            style = "colorful"
            tabWidth = 4
        [markup.tableOfContents]
            endLevel = 3
            ordered = false
            startLevel = 2
